language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
    - pip install -e .

# command to run tests
script: pytest