build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6.5
      MINICONDA: C:\Miniconda36
    - PYTHON_VERSION: 3.6.5
      MINICONDA: C:\Miniconda36-x64


matrix:
  fast_finish: true

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev .
  - pipenv run pip install colorama pandas pytest numba

test_script:
  - pipenv run python -m pytest

skip_commits:
  files:
    - docs/**/*
    - "**/*.rst"
    - "*.md"
    - ".gitignore"
    - ".travis.yml"
    - LICENSE.txt

